# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  schedule:
    - cron: "30 4 * * 5" # catch SNAPSHOT breaking changes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '21', '22-ea']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: testsuite
      - uses: actions/checkout@v4
        with:
          repository: oslc-op/refimpl
          ref: master
          path: refimpl
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'zulu'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run RefImpl
        working-directory: refimpl/src/
        run: |
          mvn -B clean package
          docker-compose -f docker-compose.yml up --build --detach
          mvn -B package --file testsuite/org.eclipse.lyo.testsuite.build/pom.xml
      - name: Run Lyo Test Suite
        working-directory: testsuite
        run: ./scripts/run-suite.sh

